spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smc
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

      #https://github.com/skarware/spring-boot-blog-app